src/Entity/Materiel.php
<?php

namespace App\Entity;

use App\Repository\MaterielRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MaterielRepository::class)]
class Materiel
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?float $prix_ht = null;

    #[ORM\ManyToOne(inversedBy: 'materiels')]
    private ?Tva $tva = null;

    #[ORM\Column]
    private ?float $prix_ttc = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrixHt(): ?float
    {
        return $this->prix_ht;
    }

    public function setPrixHt(float $prix_ht): static
    {
        $this->prix_ht = $prix_ht;

        return $this;
    }

    public function getTva(): ?Tva
    {
        return $this->tva;
    }

    public function setTva(?Tva $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getPrixTtc(): ?float
    {
        return $this->prix_ttc;
    }

    public function setPrixTtc(float $prix_ttc): static
    {
        $this->prix_ttc = $prix_ttc;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }
}

src/Form/MaterielType.php
<?php

namespace App\Form;

use App\Entity\Materiel;
use App\Entity\Tva;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MaterielType extends AbstractType
{
    /**
     * Constructeur du formulaire
     *
     * @param FormBuilderInterface $builder
     * @param array $options
     * @return void
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prix_ht', NumberType::class, [
                'label' => 'Prix HT',
            ])
            ->add('prix_ttc', NumberType::class, [
                'label' => 'Prix TTC',
            ])
            ->add('quantite', NumberType::class, [
                'label' => 'Quantité',
            ])
            ->add('date_creation', null, [
                'widget' => 'single_text',
            ])
            ->add('tva', EntityType::class, [
                'class' => Tva::class,
                'choice_label' => 'valeur',
                'label' => 'TVA (%)',
            ])
        ;
    }

    /**
     * Définition des contraintes
     *
     * @param OptionsResolver $resolver
     * @return void
    */
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Materiel::class,
        ]);
    }
}

src/Controller/MaterielController.php
<?php

namespace App\Controller;

use App\Entity\Materiel;
use App\Repository\MaterielRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\MaterielType;
use App\Services\PdfService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;

class MaterielController extends AbstractController
{
    /**
     * Récupérer tous les matériels dont la quantité est > 0
     *
     * @param MaterielRepository $materielRepository
     * @return Response
     */
    #[Route('/materiel', name: 'app_materiel')]
    public function index(MaterielRepository $materielRepository): Response
    {
        // Récupérer tous les matériels dont la quantité est > 0
        $materiels = $materielRepository->findByQty();

        return $this->render('materiel/index.html.twig', [
            'materiels' => $materiels,
        ]);
    }

    /**
     * Affichage des données d'un matériel par son id
     */
    #[Route('/materiel/detail/{id}', name: 'detail_materiel')]
    public function detail($id, MaterielRepository $materielRepository): Response
    {    
        $materiel = $materielRepository->findById($id);
        return $this->render('materiel/detail.html.twig', [
            'materiel' => $materiel,
        ]);
    }

    /**
     * Modifier un matériel
     *
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     */
    #[Route('/materiel/{id}/edit', name: 'edit_materiel')]
    public function edit(Request $request, Materiel $materiel, EntityManagerInterface $entityManager) : Response
    {
        // Créer le formulaire pour modifier le matériel
        $form = $this->createForm(MaterielType::class, $materiel);
        $form->handleRequest($request);

        // Sauvegarder les modifications si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            // Sauvegarder les modifications dans la base de données
            $entityManager->flush();

            // Redirection vers la liste des matériels
            return $this->redirectToRoute('app_materiel');
        }

        // Afficher le formulaire pour modifier le matériel
        return $this->render('materiel/edit.html.twig', [
           'materiel' => $materiel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Décrémenter la quantité d'un matériel
     *
     * @param Materiel $materiel
     * @param EntityManagerInterface $entityManager
    */
    #[Route('/materiel/decrement/{id}', name: 'materiel_decrement')]
    public function decrement(Materiel $materiel, MaterielRepository $materielRepository) : Response
    {
        // Décrémenter la quantité du matériel
        $materielRepository->decrementQty($materiel);

        // Redirection vers la page d'accueil
        return $this->redirectToRoute('app_materiel');
    }

    /**
     * Afficher un PDF des données d'un matériel
     *
     * @param Materiel $materiel
     * @param PdfService $pdfService
    */
    #[Route('/materiel/pdf/{id}', name: 'generate_pdf')]
    public function generatePdf(Materiel $materiel, PdfService $pdfService)
    {
        // Générer le contenu HTML à partir du template
        $htmlContent = $this->render('materiel/detail.html.twig', ['materiel' => $materiel]);

        // Afficher le PDF dans le navigateur
        $pdfService->showPdfFile($htmlContent);
    }
                               
}

templates/materiel/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Détails du matériel
{% endblock %}

{% block body %}

    <div class="container">
        <h1>Détails du Matériel</h1>
        <p><strong>Id :</strong> {{ materiel.id }}</p>
        <p><strong>Nom :</strong> {{ materiel.nom }}</p>
        <p><strong>Prix HT :</strong> {{ materiel.prixHt }}</span></p>
        <p><strong>TVA :</strong> {{ materiel.tva.libelle }}</p>
        <p><strong>Prix TTC :</strong> {{ materiel.prixTtc }}</span></p>
        <p><strong>Quantité :</strong> {{ materiel.quantite }}</span></p>
        <p><strong>Date de Création :</strong> {{ materiel.dateCreation ? materiel.dateCreation|date('d-m-Y') : '' }}</p>
    </div>
    
{% endblock %}

templates/materiel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le matériel{% endblock %}

{% block body %}

    <div class="container">

        <h1 class="text-center p-3">Modifier le matériel</h1>

        {{ form_start(form) }}
            <div class="row">
                <div>
                    <div class="form-group mb-3">
                        {{ form_label(form.nom) }}
                        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.nom) }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form_label(form.prix_ht) }}
                        {{ form_widget(form.prix_ht, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.prix_ht) }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form_label(form.tva) }}
                        {{ form_widget(form.tva, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.tva) }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form_label(form.prix_ttc) }}
                        {{ form_widget(form.prix_ttc, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.prix_ttc) }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form_label(form.quantite) }}
                        {{ form_widget(form.quantite, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.quantite) }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form_label(form.date_creation) }}
                        {{ form_widget(form.date_creation, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.date_creation) }}
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Valider</button>
                <a href="{{ path('app_materiel') }}" class="btn btn-secondary">Retour à la liste</a>
            </div>
        {{ form_end(form) }}    
    </div>

    <script src="{{ asset('assets/js/calcul.js') }}"></script>
    
{% endblock %}

templates/materiel/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="text-center p-3">Liste du Matériel</h1>
    <table id="materielsTable" class="display">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Prix HT</th>
                <th>TVA</th>
                <th>Prix TTC</th>
                <th>Quantité</th>
                <th>Date de création</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for materiel in materiels %}
                <tr>
                    <td>{{ materiel.id }}</td>
                    <td>{{ materiel.nom }}</td>
                    <td>{{ materiel.prixHt }}</td>
                    <td>{{ materiel.tva.libelle }}</td>
                    <td>{{ materiel.prixTtc }}</td>
                    <td>{{ materiel.quantite }}</td>
                    <td>{{ materiel.dateCreation ? materiel.dateCreation|date('d-m-Y') : '' }}</td>
                    <td>
                        <button 
                            type="button" 
                            class="btn btn-primary" 
                            data-bs-toggle="modal" 
                            data-bs-target="#materielModal"
                            data-id="{{ materiel.id }}"
                        >
                            Voir
                        </button>
                        <a href="{{ path('generate_pdf', {id: materiel.id}) }}" class="btn btn-success" target="_blank">Télécharger PDF</a>
                        <a href="{{ path('materiel_decrement', {id: materiel.id}) }}" class="btn btn-warning">Décrémenter</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {# Modal Bootstrap pour afficher les détails du matériel #}
    <div class="modal fade" id="materielModal" tabindex="-1" aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body" id="modalContent"></div>
                <div class="modal-footer">
                    <a class="btn btn-danger" id="modifierBtn">Modifier</a>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ asset('assets/js/modal.js') }}"></script>

{% endblock %}